#!/bin/bash

# upstream sources
use kubespray https://github.com/kubernetes-sigs/kubespray
#use mirantis https://github.com/Mirantis/training-lab

git remote -v | grep fetch | column -t

# stash?
# repo_is_clean || say "There are uncommitted changes in the repository. Stash them first." 1

# cross patches
patch kubespray:/contrib/terraform/aws        k8s-kubespray-aws

# hooks, are custom fn for triggers run in git-cross
cross_post_hook() {
  ask "Update upstream?" N && {
    echo "DOES NOTHING"
  }
}




